global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'yelp-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['yelp-service:8080']
  - job_name: 'nacos'
    metrics_path: /nacos/actuator/prometheus
    static_configs:
      - targets: ['nacos:8848']

