server:
  port: 8080
spring:
  application:
    name: yelp-service
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${yelp.db.host}:3306/yelp_like?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${yelp.db.pw}
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
  cloud:
    sentinel:
      eager: true
      transport:
        dashboard: ${SENTINEL_DASHBOARD:localhost:8719}
        port: ${SENTINEL_TRANSPORT_PORT:8719}
      datasource:
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.server-addr:127.0.0.1:8848}
            data-id: ${spring.application.name}-flow-rules
            group-id: SENTINEL_GROUP
            data-type: json
            rule-type: flow
logging:
  level:
    com.yelp_like: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
knife4j:
  enable: true
  openapi:
    title: 黑马商城接口文档
    description: "黑马商城接口文档"
    email: zhanghuyi@itcast.cn
    concat: 虎哥
    url: https://www.itcast.cn
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.yelp_like.controller
yelp:
  jwt:
    location: classpath:yelp_like.jks
    alias: yelp_like
    password: yelp_like123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi
# keytool -genkeypair -alias yelp_like -keyalg RSA -keypass yelp_like123 -keystore yelp_like.jks -storepass yelp_like123
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}